cp source/X_cursor cursors/X_cursor cursors/
cp source/based_arrow_down cursors/based_arrow_down
cp source/based_arrow_up cursors/based_arrow_up
cp source/boat cursors/boat
cp source/bogosity cursors/bogosity
cp source/bottom_left_corner cursors/bottom_left_corner
cp source/bottom_right_corner cursors/bottom_right_corner
cp source/bottom_side cursors/bottom_side
cp source/bottom_tee cursors/bottom_tee
cp source/box_spiral cursors/box_spiral
cp source/center_ptr cursors/center_ptr
cp source/circle cursors/circle
cp source/clock cursors/clock
cp source/coffee_mug cursors/coffee_mug
cp source/cross cursors/cross
cp source/cross_reverse cursors/cross_reverse
cp source/crosshair cursors/crosshair
cp source/diamond_cross cursors/diamond_cross
cp source/dot cursors/dot
cp source/dotbox cursors/dotbox
cp source/double_arrow cursors/double_arrow
cp source/draft_angle cursors/draft_angle
cp source/draft_small cursors/draft_small
cp source/draped_box cursors/draped_box
cp source/exchange cursors/exchange
cp source/fleur cursors/fleur
cp source/gobbler cursors/gobbler
cp source/gunby cursors/gunby
cp source/hand1 cursors/hand1
cp source/hand2 cursors/hand2
cp source/heart cursors/heart
cp source/icon cursors/icon
cp source/iron_cross cursors/iron_cross
cp source/left_side cursors/left_side
cp source/left_tee cursors/left_tee
cp source/leftbutton cursors/leftbutton
cp source/ll_angle cursors/ll_angle
cp source/lr_angle cursors/lr_angle
cp source/man cursors/man
cp source/middlebutton cursors/middlebutton
cp source/mouse cursors/mouse
cp source/pencil cursors/pencil
cp source/pirate cursors/pirate
cp source/plus cursors/plus
cp source/question_arrow cursors/question_arrow
cp source/right_ptr cursors/right_ptr
cp source/right_side cursors/right_side
cp source/right_tee cursors/right_tee
cp source/rightbutton cursors/rightbutton
cp source/rtl_logo cursors/rtl_logo
cp source/sailboat cursors/sailboat
cp source/sb_down_arrow cursors/sb_down_arrow
cp source/sb_h_double_arrow cursors/sb_h_double_arrow
cp source/sb_left_arrow cursors/sb_left_arrow
cp source/sb_right_arrow cursors/sb_right_arrow
cp source/sb_up_arrow cursors/sb_up_arrow
cp source/sb_v_double_arrow cursors/sb_v_double_arrow
cp source/shuttle cursors/shuttle
cp source/sizing cursors/sizing
cp source/spider cursors/spider
cp source/spraycan cursors/spraycan
cp source/star cursors/star
cp source/target cursors/target
cp source/tcross cursors/tcross
cp source/top_left_arrow cursors/top_left_arrow
cp source/top_left_corner cursors/top_left_corner
cp source/top_right_corner cursors/top_right_corner
cp source/top_side cursors/top_side
cp source/top_tee cursors/top_tee
cp source/trek cursors/trek
cp source/ul_angle cursors/ul_angle
cp source/umbrella cursors/umbrella
cp source/ur_angle cursors/ur_angle
cp source/watch cursors/watch
